"""empty message

Revision ID: 096564a61359
Revises: 
Create Date: 2020-08-23 00:55:53.050302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096564a61359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VGenres',
    sa.Column('genre', sa.Enum('Alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genres'), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vid'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre', 'vid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VGenres')
    # ### end Alembic commands ###
