"""empty message

Revision ID: 52111d45780f
Revises: 5881225d9f48
Create Date: 2020-08-25 20:53:58.568044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52111d45780f'
down_revision = '5881225d9f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
