"""empty message

Revision ID: a1a967fb7b31
Revises: 579dfeda537c
Create Date: 2020-08-25 02:14:57.702972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a967fb7b31'
down_revision = '579dfeda537c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGenres',
    sa.Column('agenre', sa.Enum('Alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='agenres'), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('agenre', 'aid')
    )
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    op.drop_table('AGenres')
    # ### end Alembic commands ###
